server:
  extraArgs:
    - --insecure 

  service:
    type: ClusterIP

  ingress:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      nginx.org/hsts: "false"
      cert-manager.io/cluster-issuer: issuer
    hosts:
      - argocd.hassan114.click
    tls:
      - secretName: argocd-ingress-tls
        hosts:
          - argocd.hassan114.click