name: Terraform Apply

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write

env:
  AWS_REGION: eu-west-1
  TF_WORKING_DIR: ./terraform
  TF_VAR_SOURCE_AUTH_PASSWORD: ${{ secrets.SOURCE_AUTH_PASSWORD }}

jobs:
  # Manual Approval Step
  manual-approval:
    name: Manual Approval Required
    runs-on: ubuntu-latest

    steps:
      - name: Await Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.GITHUB_TOKEN }}
          approvers: hassan114h
          minimum-approvals: 1
          issue-title: "Approval Required for Terraform Apply"
          issue-body: "Approve or deny applying the previously generated Terraform plan."
          exclude-workflow-initiator-as-approver: false

  # Terraform Apply Stage
  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: manual-approval

    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::<913513914993:role/OIDC_ROLE
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ${{ env.TF_WORKING_DIR }}

      - name: Download Lockfile
        uses: actions/download-artifact@v4
        with:
          name: tf-lockfile
          path: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply Using Approved Plan
        run: terraform apply -auto-approve tfplan
